// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZm_qIMvCY6vp0Xb_mSIzlwM_Sf-4Ias4',
    appId: '1:221298954934:web:f5ffdcb4509ef91a480c17',
    messagingSenderId: '221298954934',
    projectId: 'xo-rymaz-wear',
    authDomain: 'xo-rymaz-wear.firebaseapp.com',
    storageBucket: 'xo-rymaz-wear.firebasestorage.app',
    measurementId: 'G-84TVT4YWT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6qBm8tkYYYRIHRqslZNc7jXJ_g2xg6Q',
    appId: '1:221298954934:android:c24c48dca6725ae6480c17',
    messagingSenderId: '221298954934',
    projectId: 'xo-rymaz-wear',
    storageBucket: 'xo-rymaz-wear.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTdXkTO_tMJFNXCJqU7ljlxO6TD-1h2L4',
    appId: '1:221298954934:ios:4b88a6e25243f644480c17',
    messagingSenderId: '221298954934',
    projectId: 'xo-rymaz-wear',
    storageBucket: 'xo-rymaz-wear.firebasestorage.app',
    iosClientId: '221298954934-m2e3nkj3u80dddstob64e7i4li0uk2k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTdXkTO_tMJFNXCJqU7ljlxO6TD-1h2L4',
    appId: '1:221298954934:ios:4b88a6e25243f644480c17',
    messagingSenderId: '221298954934',
    projectId: 'xo-rymaz-wear',
    storageBucket: 'xo-rymaz-wear.firebasestorage.app',
    iosClientId: '221298954934-m2e3nkj3u80dddstob64e7i4li0uk2k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZm_qIMvCY6vp0Xb_mSIzlwM_Sf-4Ias4',
    appId: '1:221298954934:web:e9f9f54832115549480c17',
    messagingSenderId: '221298954934',
    projectId: 'xo-rymaz-wear',
    authDomain: 'xo-rymaz-wear.firebaseapp.com',
    storageBucket: 'xo-rymaz-wear.firebasestorage.app',
    measurementId: 'G-5Z4L6D3TWW',
  );
}
